# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-25 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=15)),
                ('last_login', models.DateTimeField()),
                ('place', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('job', models.CharField(max_length=50)),
            ],
        ),
    ]
